[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_program = "61sh4SDsMdTvpcWguGERE7HtRJoWMxG3QjRRQk8aiVTq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cypher/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
