[package]
name = "solana_stake_account"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-client = "2.1.2"
solana-program = "2.1.2"
solana-sdk = "2.1.2"
