[features]
seeds = false
skip-lint = false
[programs.localnet]
matchmaking = "2h8AUNUnGPg1RBLEhi6K82rLBypBmp5gHoSAGwBArp3X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cypher/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
