name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.0/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Check solana-cli version
        run: |
          if solana --version | grep -q "solana-cli 1.18"; then
            echo "solana-cli version is 1.18"
          else
            echo "::warning::Warning: $SOLANA_VERSION is not 1.18. Please ensure you are using the correct version."
          fi

      - name: Set up Rust 1.80.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.80.0'
          override: true
          components: rustfmt

#      - name: Verify Rust Version
#        run: |
#          REQUIRED_RUST_VERSION="1.80.0"
#          INSTALLED_RUST_VERSION=$(rustc --version | awk '{print $2}')
#          if [[ "$INSTALLED_RUST_VERSION" < "$REQUIRED_RUST_VERSION" ]]; then
#            echo "Rust version is below required 1.80.0; updating to 1.80.0"
#            rustup install 1.80.0
#            rustup default 1.80.0
#          else
#            echo "Rust version is up-to-date: $INSTALLED_RUST_VERSION"
#          fis

      - name: Install Anchor
        run: |
          run: cargo install --git https://github.com/project-serum/anchor --tag v0.30.1

      - name: Run Anchor tests
        run: |
          cd programs/your_program simple-staker
          anchor test --skip-deploy

      # Below will be uncommented after anchor update.    
      #- name: Build Solana program
      #  run: |
      #    cd program
      #    cargo update -p solana-program@1.18.23 --precise ver
      #    cargo build-bpf --manifest-path=Cargo.toml


      #- name: Run Unit Tests
      #  run: |
      #    cd program
      #    cargo test
