name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.0/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Check solana-cli version
        run: |
          if solana --version | grep -q "solana-cli 1.18"; then
            echo "solana-cli version is 1.18"
          else
            echo "::warning::Warning: $SOLANA_VERSION is not 1.18. Please ensure you are using the correct version."
          fi

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Build Solana program
        run: |
          cd program
          cargo build-bpf --manifest-path=Cargo.toml

      - name: Run Unit Tests
        run: |
          cd program
          cargo test
          cd ../js
          npm test # Ensure you have unit tests configured in your package.json
